spring:
  application:
    name: bookstore
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bookstore}
    username: ${SPRING_DATASOURCE_USERNAME:bookstore}
    password: ${SPRING_DATASOURCE_PASSWORD:bookstore}
  jpa:
    hibernate:
      ddl-auto: validate        # schemat tworzy Flyway, Hibernate tylko waliduje
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
