CREATE TABLE authors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    role       VARCHAR(20)  NOT NULL,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE books (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_type        VARCHAR(31)  NOT NULL,
    title            VARCHAR(255) NOT NULL,
    isbn             VARCHAR(255) NOT NULL UNIQUE,
    author_id        BIGINT       NOT NULL REFERENCES authors (id),
    price            NUMERIC(10, 2) NOT NULL,
    total_copies     INTEGER      NOT NULL,
    available_copies INTEGER      NOT NULL,
    -- PrintedBook
    pages            INTEGER,
    cover_type       VARCHAR(255),
    -- Ebook
    file_format      VARCHAR(255),
    file_size_mb     NUMERIC(6, 2),
    -- Audiobook
    duration_minutes INTEGER,
    narrator         VARCHAR(255)
);

CREATE TABLE loans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    book_id     BIGINT      NOT NULL REFERENCES books (id),
    status      VARCHAR(20) NOT NULL,
    reserved_at TIMESTAMPTZ,
    borrowed_at TIMESTAMPTZ,
    due_at      TIMESTAMPTZ,
    returned_at TIMESTAMPTZ,
    penalty     NUMERIC(10, 2) NOT NULL DEFAULT 0
);
